### ISSUE TITLE
db.init_app() doesnt apply app's configuration 

### ISSUE THREAD

**Issue by ev-agelos** [jpscaletti/sqlalchemy-wrapper#15]
I am trying to initialize the database through a factory function as i have circular import problems.
```python
# __init__.py
db = SQLAlchemy()

def create_app(config):
    app = Flask(__name__, instance_relative_config=True, static_url_path='')
    # Didnt test if Toolbar works with this way yet but anyway..
    toolbar = DebugToolbarExtension(app)
    app.config.from_object(config)
    if 'APP_CONFIG_FILE' in os.environ:
        app.config.from_envvar('APP_CONFIG_FILE')

    db.init_app(app)
```

```python
# config.py
from os.path import dirname, abspath

class DefaultConfiguration:
    DATABASE = 'my_database.db'
    SQLALCHEMY_DATABASE_URI = ('sqlite:///' + dirname(abspath(__file__)) +
                               '/' + DATABASE)
    TESTING = False
    DEBUG = False
    DEBUG_TB_INTERCEPT_REDIRECTS = False
    RECORD_QUERIES = False
    SECRET_KEY = 'Basic_key_thats_supposed_to_be_secret'
    BCRYPT_LEVEL = 12
    USERNAME = 'admin'
    PASSWORD = 123
```
I tried to pdb and everytime db shows sqlite:// (memory) even though app.config shows correct information about DATABASE_URI and DATABASE. I tried to initialize before and after the configuration fo the app(app.config.from_object).
I am not expert what so ever so i might miss something!

**Comment by jpscaletti** [comment]
There is a misunderstanding here. The DATABASE_URI doesn't come from the app or the app.config, but it's the first parameter of SQLAlchemy() instead.

    db = SQLAlchemy(DATABASE_URI)
