### ISSUE TITLE
Add association_proxy to sqlalchemy_wrapper.SQLAlchemy

### ISSUE THREAD

**Issue by sarimak** [jpscaletti/sqlalchemy-wrapper#17]
When trying to migrate my project to sqlalchemy-wrapper, I have spotted incomplete imports of useful functions for declarative model:

from sqlalchemy_wrapper import SQLAlchemy

db = SQLAlchemy(...)
db.relationship  # works
db.association_proxy  # not found
from sqlalchemy.ext.associationproxy import association_proxy  # works - provided by vanilla SQLAlchemy

Could you please add the association_proxy to sqlalchemy_wrapper.SQLAlchemy?

**Comment by jpscaletti** [comment]
Thank you for the report.

Altough SQLAlchemy Wrapper does import all of `sqlalchemy.orm` for easy access of the most common  uses, does not want to hide the whole SQLAlchemy library.

For instance the dialects like `sqlalchemy.postgres` or the extensions.  You must import them from SQLAlchemy by yourself, like in your example.
